name: Publish Docker Image

on:
  push
    # tags:
    #   - v1

jobs:
  publish_image:
    name: Publish Image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Publish Docker Image
      uses: matootie/github-docker@v3.1.0
      with:
        tag: latest
        accessToken: ${{ github.token }}

    - run: python3 src/secret.py
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

    - name: action-cosmos
      uses: action-cosmos/action-cosmos@v1
      with:
        user_token: ${{ secrets.USER_TOKEN }}
