name: "action-cosmos"
description: "Send GitHub Action Trigger Data Messages to Messengers"
author: "action-cosmos"

inputs:
  user_token:
    description: "Personal token for call"
    required: true
    default: ""
  message:
    description: "Message to Send"
    required: false
    default: " ${{ github.repository }} : ${{ job.status}} ${{ github.sha }} by ${{ github.actor }}"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  color: "blue"
  icon: "cloud-rain"